/*
* Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
* Generated by MATLAB(R) 8.4 and the Signal Processing Toolbox 6.22.
* Generated on: 04-Sep-2016 10:59:27
*/

/*
* Discrete-Time FIR Filter (real)
* -------------------------------
* Filter Structure  : Direct-Form FIR
* Filter Length     : 20
* Stable            : Yes
* Linear Phase      : Yes (Type 2)
*/

/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"
/*
* Expected path to tmwtypes.h
* D:\Softwares\Matlab2014b\extern\include\tmwtypes.h
*/
const int BL3 = 20;
const double B3[20] = {
	-0.01199982441241, -0.01205344595842, 0.004859465156719, 0.01592252448549,
	-0.02437005583196, -0.1154719491298, -0.171477060932, -0.09163668495805,
	0.1129352861698, 0.292324215204, 0.292324215204, 0.1129352861698,
	-0.09163668495805, -0.171477060932, -0.1154719491298, -0.02437005583196,
	0.01592252448549, 0.004859465156719, -0.01205344595842, -0.01199982441241
};
