/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mrcheng_myapplication_MyThread */

#ifndef _Included_mrcheng_myapplication_MyThread
#define _Included_mrcheng_myapplication_MyThread
#ifdef __cplusplus
extern "C" {
#endif
#undef mrcheng_myapplication_MyThread_MIN_PRIORITY
#define mrcheng_myapplication_MyThread_MIN_PRIORITY 1L
#undef mrcheng_myapplication_MyThread_NORM_PRIORITY
#define mrcheng_myapplication_MyThread_NORM_PRIORITY 5L
#undef mrcheng_myapplication_MyThread_MAX_PRIORITY
#define mrcheng_myapplication_MyThread_MAX_PRIORITY 10L
/*
 * Class:     mrcheng_myapplication_MyThread
 * Method:    getStringFromNative
 * Signature: ([S[D)V
 */
JNIEXPORT void JNICALL Java_mrcheng_myapplication_MyThread_getStringFromNative
  (JNIEnv *, jobject, jshortArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
